/**
 * 赢日志 - 本地轻量级 Express 数据库及 AI 转发服务
 */
const express = require('express');
const fs = require('fs');
const path = require('path');
const cors = require('cors');

const app = express();
const PORT = 3001;
const DB_FILE = path.join(__dirname, 'db.json');

app.use(cors());
app.use(express.json());

// 托管前端打包后的静态资源 (供服务器单包部署使用)
app.use(express.static(path.join(__dirname, 'dist')));

// 初始化 db.json
function initDB() {
  if (!fs.existsSync(DB_FILE)) {
    const defaultData = {
      logs: {},
      settings: {
        job: 'frontend',
        tone: 'professional',
        similarityThreshold: 50,
        rollingDays: 7
      }
    };
    fs.writeFileSync(DB_FILE, JSON.stringify(defaultData, null, 2), 'utf8');
  }
}

// 读取数据
function readDB() {
  initDB();
  try {
    const data = fs.readFileSync(DB_FILE, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    console.error('读取数据库失败:', error);
    return { logs: {}, settings: {} };
  }
}

// 写入数据
function writeDB(data) {
  try {
    fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf8');
    return true;
  } catch (error) {
    console.error('写入数据库失败:', error);
    return false;
  }
}

// API: 获取所有日志与配置
app.get('/api/data', (req, res) => {
  const data = readDB();
  res.json(data);
});

// API: 保存单条日志
app.post('/api/logs', (req, res) => {
  const { date, title, hours, cooperation, difficulty, content, job, tone, isAutoGenerated } = req.body;
  if (!date || !content) {
    return res.status(400).json({ error: '缺少 date 或 content 参数' });
  }

  const data = readDB();
  data.logs[date] = {
    title: title || '日常前端开发工作',
    hours: hours !== undefined ? Number(hours) : 8,
    cooperation: !!cooperation,
    difficulty: !!difficulty,
    content,
    job,
    tone,
    isAutoGenerated,
    updatedAt: new Date().toISOString()
  };

  if (writeDB(data)) {
    res.json({ success: true, log: data.logs[date] });
  } else {
    res.status(500).json({ error: '保存日志失败' });
  }
});

// API: 删除单条日志
app.delete('/api/logs/:date', (req, res) => {
  const { date } = req.params;
  const data = readDB();
  
  if (data.logs[date]) {
    delete data.logs[date];
    if (writeDB(data)) {
      return res.json({ success: true });
    }
  }
  res.status(404).json({ error: '日志不存在或删除失败' });
});

// API: 保存用户常规业务配置
app.post('/api/settings', (req, res) => {
  const { job, tone, similarityThreshold, rollingDays, customTemplates } = req.body;
  const data = readDB();

  data.settings = {
    ...data.settings,
    job: job || data.settings.job,
    tone: tone || data.settings.tone,
    similarityThreshold: similarityThreshold !== undefined ? similarityThreshold : data.settings.similarityThreshold,
    rollingDays: rollingDays !== undefined ? Number(rollingDays) : data.settings.rollingDays || 7,
    customTemplates: customTemplates || data.settings.customTemplates
  };

  if (writeDB(data)) {
    res.json({ success: true, settings: data.settings });
  } else {
    res.status(500).json({ error: '保存配置失败' });
  }
});

// API: 恢复出厂设置
app.post('/api/reset', (req, res) => {
  const defaultData = {
    logs: {},
    settings: {
      job: 'frontend',
      tone: 'professional',
      similarityThreshold: 50,
      rollingDays: 7
    }
  };
  if (writeDB(defaultData)) {
    res.json({ success: true });
  } else {
    res.status(500).json({ error: '重置数据库失败' });
  }
});

// API: 在线调用 AI 生成日报 (多用户 Key 隔离中转代理模式，后端零留存)
app.post('/api/generate', async (req, res) => {
  const { userInput, job, aiApiKey, aiApiUrl, aiModel } = req.body;

  if (!aiApiKey) {
    return res.status(400).json({ error: '在线大模型接口未配置 API 密钥 (API Key)！' });
  }

  const jobName = job === 'designer' ? 'UI/UX 视觉设计师' : '前端开发工程师';
  const tasksText = (userInput && userInput.trim())
    ? `【${userInput.trim()}】`
    : '“日常基础代码库维护与细节调优（今天没有特定大需求上线，主要进行排错与代码整理自测）”';

  const examples = job === 'designer' ? `
* ❌ 反面例子（太虚太浮夸，HR一眼看穿是AI）：
“针对产品核心展示模块进行了全方位的交互体验设计与视觉包装升级，构建了高复用的视觉规范，显著提升了页面在跨终端环境下的用户体感和开发对接效率。”
* 🟢 正面例子（非常写实自然，工作量饱和）：
“跟产品对了对下期需求的线框图，理了理几个复杂的页面跳转逻辑。下午把这期核心的高保真视觉设计稿细化了下，顺便把本地图层重新命名归档整理了下，给云盘腾了腾空间。”
` : `
* ❌ 反面例子（太虚太浮夸，HR一眼看穿是AI）：
“深度重构了系统核心列表渲染组件，引入了基于虚拟滚动的高效异步加载算法，成功缩减了打包体积，显著优化了页面在低端机型下的首屏交互流畅度。”
* 🟢 正面例子（非常写实自然，工作量饱和）：
“把首页列表数据多的时候有点卡顿的问题给优化了下，改成了按需懒加载渲染。顺手把项目打包的配置文件精简了下，清理了几个过期不用的包，在本地跑了下回归测试。”
`;

  const systemPrompt = `你是一个在公司里默默搬砖、踏实干活的专业 ${jobName}。请帮我写一份日常工作日志。`;
  const userPrompt = `今天我做的工作是：${tasksText}。请帮我写一份日常工作日志。

要求：
1. 语气必须高度口语化、平实写实，像真人随手写的流水账。绝对不要有任何浮夸的 AI 腔调和官腔（多用“改了改”、“调了调”、“排查了”、“修了一下”、“对了一下”，绝对不要用“重构了冗余逻辑”、“显著提升了性能”、“优化了打包体积”等浮夸词汇）。
2. 工作量显得“饱满且充实”。如果我给出的工作内容比较简短，请帮我在合理的专业范围内进行步骤展开（比如把“写了登录”合理扩展拆解为：画页面布局、处理表单参数校验、联调接口以及本地跑自测等）。
3. 增加一点点口语化的工作细节（比如“把 Figma 的间距标注仔细对了一遍”、“把控制台里的几个警告日志清理了一下”等），让日报显得极其真实。
4. 字数控制在 100 - 150 字之间，分条列出（2-3条即可）。
5. 顺便帮我起一个 15 字以内的极简日志标题。

请参考并对比以下写作风格：
${examples}

请严格按照以下格式直接输出（不要有任何多余的 Markdown 代码块或前后缀解释说明）：
标题：[极简日志标题]
内容：
1. [第一条工作内容，大白话口语，写实有细节]
2. [第二条工作内容，大白话口语，写实有细节]`;

  try {
    const apiBaseUrl = aiApiUrl || 'https://openrouter.ai/api/v1';
    const apiUrl = apiBaseUrl.endsWith('/') ? apiBaseUrl + 'chat/completions' : apiBaseUrl + '/chat/completions';
    
    const response = await fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'Authorization': `Bearer ${aiApiKey}`
      },
      body: JSON.stringify({
        model: aiModel || 'qwen/qwen-3-coder:free',
        messages: [
          { role: 'system', content: systemPrompt },
          { role: 'user', content: userPrompt }
        ],
        temperature: 0.7,
        max_tokens: 500
      })
    });

    if (!response.ok) {
      const errText = await response.text();
      throw new Error(`API 平台响应错误: ${response.status} - ${errText}`);
    }

    const apiData = await response.json();
    const rawText = apiData.choices[0].message.content.trim();

    // 解析
    let title = '日常开发工作';
    let content = rawText;

    const titleMatch = rawText.match(/标题：\s*(.+)/);
    const contentMatch = rawText.match(/内容：\s*([\s\S]+)/);

    if (titleMatch && titleMatch[1]) {
      title = titleMatch[1].trim();
    }
    if (contentMatch && contentMatch[1]) {
      content = contentMatch[1].trim();
    }

    res.json({ success: true, title, content });
  } catch (error) {
    console.error('在线 AI 生成请求失败:', error);
    res.status(500).json({ error: error.message || '大模型生成请求失败' });
  }
});

// API: 动态拉取并同步大模型列表 (中转转发 /v1/models)
app.post('/api/models', async (req, res) => {
  const { aiApiKey, aiApiUrl } = req.body;
  if (!aiApiKey) {
    return res.status(400).json({ error: '请先填入 API 密钥以获取模型列表！' });
  }

  try {
    const apiBaseUrl = aiApiUrl || 'https://openrouter.ai/api/v1';
    const modelsUrl = apiBaseUrl.endsWith('/') ? apiBaseUrl + 'models' : apiBaseUrl + '/models';

    const response = await fetch(modelsUrl, {
      method: 'GET',
      headers: {
        'Authorization': `Bearer ${aiApiKey}`
      }
    });

    if (!response.ok) {
      throw new Error(`获取模型列表失败: ${response.status}`);
    }

    const apiData = await response.json();
    
    // 清洗模型数据，标记免费模型
    const models = (apiData.data || []).map(m => {
      let isFree = false;
      if (m.id.includes(':free') || m.id.includes('-free')) {
        isFree = true;
      }
      if (m.pricing && Number(m.pricing.prompt) === 0 && Number(m.pricing.completion) === 0) {
        isFree = true;
      }
      
      return {
        id: m.id,
        name: m.name || m.id,
        isFree
      };
    });

    res.json({ success: true, models });
  } catch (error) {
    console.error('获取大模型列表失败:', error);
    res.status(500).json({ error: error.message || '拉取大模型列表失败' });
  }
});

// 前端路由通配托管 (支持 React 路由 SPA 刷新不报 404)
app.get('*', (req, res) => {
  res.sendFile(path.join(__dirname, 'dist', 'index.html'));
});

app.listen(PORT, () => {
  console.log(`Backend Database Server is running on http://localhost:${PORT}`);
});
