import express from 'express';
import cors from 'cors';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const DB_FILE = path.join(__dirname, 'db.json');

const app = express();
const PORT = 3001;

app.use(cors());
app.use(express.json());

// 初始化 db.json
function initDB() {
  if (!fs.existsSync(DB_FILE)) {
    const defaultData = {
      logs: {},
      settings: {
        job: 'frontend',
        tone: 'professional',
        similarityThreshold: 50,
        rollingDays: 7
      }
    };
    fs.writeFileSync(DB_FILE, JSON.stringify(defaultData, null, 2), 'utf8');
  }
}

// 读取数据
function readDB() {
  initDB();
  try {
    const data = fs.readFileSync(DB_FILE, 'utf8');
    return JSON.parse(data);
  } catch (error) {
    console.error('读取数据库失败:', error);
    return { logs: {}, settings: {} };
  }
}

// 写入数据
function writeDB(data) {
  try {
    fs.writeFileSync(DB_FILE, JSON.stringify(data, null, 2), 'utf8');
    return true;
  } catch (error) {
    console.error('写入数据库失败:', error);
    return false;
  }
}

// API: 获取所有日志与配置
app.get('/api/data', (req, res) => {
  const data = readDB();
  res.json(data);
});

// API: 保存单条日志，适配新的表单字段
app.post('/api/logs', (req, res) => {
  const { date, title, hours, cooperation, difficulty, content, job, tone, isAutoGenerated } = req.body;
  if (!date || !content) {
    return res.status(400).json({ error: '缺少 date 或 content 参数' });
  }

  const data = readDB();
  data.logs[date] = {
    title: title || '日常前端开发工作',
    hours: hours !== undefined ? Number(hours) : 8,
    cooperation: !!cooperation,
    difficulty: !!difficulty,
    content,
    job,
    tone,
    isAutoGenerated,
    updatedAt: new Date().toISOString()
  };

  if (writeDB(data)) {
    res.json({ success: true, log: data.logs[date] });
  } else {
    res.status(500).json({ error: '保存日志失败' });
  }
});

// API: 删除单条日志
app.delete('/api/logs/:date', (req, res) => {
  const { date } = req.params;
  const data = readDB();
  
  if (data.logs[date]) {
    delete data.logs[date];
    if (writeDB(data)) {
      return res.json({ success: true });
    }
  }
  res.status(404).json({ error: '日志不存在或删除失败' });
});

// API: 保存用户配置
app.post('/api/settings', (req, res) => {
  const { job, tone, similarityThreshold, rollingDays, customTemplates } = req.body;
  const data = readDB();

  data.settings = {
    ...data.settings,
    job: job || data.settings.job,
    tone: tone || data.settings.tone,
    similarityThreshold: similarityThreshold !== undefined ? similarityThreshold : data.settings.similarityThreshold,
    rollingDays: rollingDays !== undefined ? Number(rollingDays) : data.settings.rollingDays || 7,
    customTemplates: customTemplates || data.settings.customTemplates
  };

  if (writeDB(data)) {
    res.json({ success: true, settings: data.settings });
  } else {
    res.status(500).json({ error: '保存配置失败' });
  }
});

app.listen(PORT, () => {
  console.log(`Backend Database Server is running on http://localhost:${PORT}`);
});
