/**
 * 请求失败分类回归测试
 *
 * 核心契约：只有「网络不可达」才允许降级入队并对外声称成功；
 * 服务端明确拒绝（401/4xx/5xx）必须返回 success:false 且严禁入队，
 * 否则会出现「UI 报保存成功、数据其实没落盘、队列还被永久堵死」的问题。
 */
import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import {
  saveLog,
  deleteLog,
  resetAllData,
  syncOfflineOperations,
  AUTH_EXPIRED_EVENT,
  setAuthToken
} from '../storage';
import { clearOfflineQueue, getOfflineQueue, enqueue } from '../offlineQueue';

const LOG_DATA = {
  title: '测试日志',
  hours: 8,
  cooperation: false,
  difficulty: false,
  content: '测试内容，用于校验失败分类逻辑。',
  job: 'frontend',
  tone: 'professional',
  isAutoGenerated: false
};

/** 构造一个返回指定状态码的 fetch 替身 */
function mockHttp(status: number, body: unknown = { error: '服务端拒绝' }) {
  return vi.fn().mockResolvedValue(
    new Response(JSON.stringify(body), {
      status,
      headers: { 'Content-Type': 'application/json' }
    })
  );
}

/** 构造一个网络层直接抛错的 fetch 替身 */
function mockNetworkDown(name = 'TypeError') {
  const err = new Error('fetch failed');
  err.name = name;
  return vi.fn().mockRejectedValue(err);
}

describe('storage 请求失败分类', () => {
  let mockStore: Record<string, string> = {};
  let events: string[] = [];

  beforeEach(() => {
    mockStore = {};
    (globalThis as any).localStorage = {
      getItem: (key: string) => mockStore[key] || null,
      setItem: (key: string, value: string) => { mockStore[key] = String(value); },
      removeItem: (key: string) => { delete mockStore[key]; },
      clear: () => { mockStore = {}; },
      length: 0,
      key: (_i: number) => null
    };
    events = [];
    (globalThis as any).window = {
      dispatchEvent: (ev: any) => { events.push(ev.type); return true; },
      addEventListener: () => {},
      removeEventListener: () => {}
    };
    (globalThis as any).CustomEvent = class {
      type: string;
      detail: any;
      constructor(type: string, init?: any) { this.type = type; this.detail = init?.detail; }
    };
    clearOfflineQueue();
    mockStore = {};
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('网络不可达时应降级入队，并对外声称已本地保存', async () => {
    globalThis.fetch = mockNetworkDown() as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.success).toBe(true);
    expect(res.isOffline).toBe(true);
    expect(getOfflineQueue()).toHaveLength(1);
    expect(getOfflineQueue()[0].kind).toBe('save_log');
  });

  it('请求超时应视为离线并入队', async () => {
    globalThis.fetch = mockNetworkDown('TimeoutError') as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.isOffline).toBe(true);
    expect(getOfflineQueue()).toHaveLength(1);
  });

  it('401 必须返回失败、不入队，并派发登录失效事件', async () => {
    setAuthToken('expired_token');
    globalThis.fetch = mockHttp(401, { error: '登录凭证已过期或签名无效，请重新登录。' }) as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.success).toBe(false);
    expect(res.isOffline).toBe(false);
    expect(res.error).toContain('登录凭证');
    expect(getOfflineQueue()).toHaveLength(0);
    expect(events).toContain(AUTH_EXPIRED_EVENT);
    // 失效凭证应被清除，避免后续请求继续携带
    expect(mockStore['winner_daily_token']).toBeUndefined();
  });

  it('400 参数错误必须返回失败且不入队（重试永远不会成功）', async () => {
    globalThis.fetch = mockHttp(400, { error: '缺少 date 或 content 参数' }) as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.success).toBe(false);
    expect(res.error).toBe('缺少 date 或 content 参数');
    expect(getOfflineQueue()).toHaveLength(0);
  });

  it('500 写盘失败必须上报给用户，而不是伪装成离线', async () => {
    globalThis.fetch = mockHttp(500, { error: '保存日志失败' }) as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.success).toBe(false);
    expect(res.error).toBe('保存日志失败');
    expect(getOfflineQueue()).toHaveLength(0);
  });

  it('503 网关不可用应等同离线并入队重试', async () => {
    globalThis.fetch = mockHttp(503, {}) as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.success).toBe(true);
    expect(res.isOffline).toBe(true);
    expect(getOfflineQueue()).toHaveLength(1);
  });

  it('2xx 成功时不得入队', async () => {
    globalThis.fetch = mockHttp(200, { success: true }) as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.success).toBe(true);
    expect(res.isOffline).toBe(false);
    expect(getOfflineQueue()).toHaveLength(0);
  });

  it('删除被服务端拒绝时不得入队', async () => {
    globalThis.fetch = mockHttp(404, { error: '日志不存在或删除失败' }) as any;

    const res = await deleteLog('2026-09-01');

    expect(res.success).toBe(false);
    expect(res.error).toBe('日志不存在或删除失败');
    expect(getOfflineQueue()).toHaveLength(0);
  });

  it('重置被服务端拒绝时必须保留本地数据且不入队', async () => {
    mockStore['winner_daily_data'] = JSON.stringify({ logs: { '2026-09-01': LOG_DATA } });
    globalThis.fetch = mockHttp(500, { error: '重置数据库失败' }) as any;

    const res = await resetAllData();

    expect(res.success).toBe(false);
    expect(res.error).toBe('重置数据库失败');
    expect(getOfflineQueue()).toHaveLength(0);
    // 本地数据不得被单边清除
    expect(mockStore['winner_daily_data']).toContain('2026-09-01');
  });

  it('HTML 响应（SPA 通配兜底）不得作为错误文案透出', async () => {
    globalThis.fetch = vi.fn().mockResolvedValue(
      new Response('<!doctype html><html><body>fallback</body></html>', {
        status: 404,
        headers: { 'Content-Type': 'text/html' }
      })
    ) as any;

    const res = await saveLog('2026-09-01', LOG_DATA);

    expect(res.success).toBe(false);
    expect(res.error).toBe('服务端返回 HTTP 404');
  });
});

describe('离线队列回放的失败处置', () => {
  let mockStore: Record<string, string> = {};

  beforeEach(() => {
    mockStore = {};
    (globalThis as any).localStorage = {
      getItem: (key: string) => mockStore[key] || null,
      setItem: (key: string, value: string) => { mockStore[key] = String(value); },
      removeItem: (key: string) => { delete mockStore[key]; },
      clear: () => { mockStore = {}; },
      length: 0,
      key: (_i: number) => null
    };
    (globalThis as any).window = {
      dispatchEvent: () => true,
      addEventListener: () => {},
      removeEventListener: () => {}
    };
    clearOfflineQueue();
    mockStore = {};
  });

  afterEach(() => {
    vi.restoreAllMocks();
  });

  it('4xx 永久性拒绝的条目必须被丢弃，否则会永久堵死整个 FIFO 队列', async () => {
    enqueue({ kind: 'save_log', date: '2026-09-01', payload: { date: '2026-09-01', ...LOG_DATA } });
    enqueue({ kind: 'save_log', date: '2026-09-02', payload: { date: '2026-09-02', ...LOG_DATA } });

    // 第一条被永久拒绝，第二条正常
    let call = 0;
    globalThis.fetch = vi.fn().mockImplementation(() => {
      call++;
      const status = call === 1 ? 400 : 200;
      return Promise.resolve(
        new Response(JSON.stringify(call === 1 ? { error: '载荷非法' } : { success: true }), {
          status,
          headers: { 'Content-Type': 'application/json' }
        })
      );
    }) as any;

    const res = await syncOfflineOperations();

    expect(res.droppedCount).toBe(1);
    expect(res.successCount).toBe(1);
    expect(res.lastError).toBe('载荷非法');
    // 队列必须被清空，不能因为毒丸条目卡住
    expect(getOfflineQueue()).toHaveLength(0);
  });

  it('401 应保留队列等待重新登录后回放，不得丢弃用户数据', async () => {
    enqueue({ kind: 'save_log', date: '2026-09-01', payload: { date: '2026-09-01', ...LOG_DATA } });
    globalThis.fetch = mockHttp(401, { error: '登录凭证已失效' }) as any;

    const res = await syncOfflineOperations();

    expect(res.droppedCount).toBe(0);
    expect(res.successCount).toBe(0);
    expect(getOfflineQueue()).toHaveLength(1);
  });

  it('5xx 服务端暂时故障应保留队列重试', async () => {
    enqueue({ kind: 'save_log', date: '2026-09-01', payload: { date: '2026-09-01', ...LOG_DATA } });
    globalThis.fetch = mockHttp(500, { error: '写盘失败' }) as any;

    const res = await syncOfflineOperations();

    expect(res.droppedCount).toBe(0);
    expect(getOfflineQueue()).toHaveLength(1);
  });

  it('网络仍不可达时应完整保留队列', async () => {
    enqueue({ kind: 'save_log', date: '2026-09-01', payload: { date: '2026-09-01', ...LOG_DATA } });
    globalThis.fetch = mockNetworkDown() as any;

    const res = await syncOfflineOperations();

    expect(res.droppedCount).toBe(0);
    expect(getOfflineQueue()).toHaveLength(1);
  });
});
