import express from 'express';
import { readDB, writeDB, createDefaultSettings } from '../db.js';
import { authMiddleware } from '../middleware/auth.js';

const router = express.Router();

// 统一应用鉴权中间件
router.use(authMiddleware);

// API: 获取该特定用户的所有日志与配置
router.get('/data', (req, res) => {
  const username = req.username;
  const db = readDB();
  res.json({
    logs: db.users[username].logs || {},
    settings: db.users[username].settings || {}
  });
});

// API: 保存单条日志 (支持用户维度写入)
router.post('/logs', (req, res) => {
  const username = req.username;
  const { date, title, hours, cooperation, difficulty, content, job, customJobName, tone, isAutoGenerated } = req.body;
  if (!date || !content) {
    return res.status(400).json({ error: '缺少 date 或 content 参数' });
  }

  const db = readDB();
  db.users[username].logs[date] = {
    title: title || '日常工作日志',
    hours: hours !== undefined ? Number(hours) : 8,
    cooperation: !!cooperation,
    difficulty: !!difficulty,
    content,
    job,
    customJobName,
    tone,
    isAutoGenerated,
    updatedAt: new Date().toISOString()
  };

  if (writeDB(db)) {
    res.json({ success: true, log: db.users[username].logs[date] });
  } else {
    res.status(500).json({ error: '保存日志失败' });
  }
});

// API: 删除单条日志 (支持用户维度删除)
router.delete('/logs/:date', (req, res) => {
  const username = req.username;
  const { date } = req.params;
  const db = readDB();

  if (db.users[username] && db.users[username].logs[date]) {
    delete db.users[username].logs[date];
    if (writeDB(db)) {
      return res.json({ success: true });
    }
  }
  res.status(404).json({ error: '日志不存在或删除失败' });
});

// API: 保存用户配置
router.post('/settings', (req, res) => {
  const username = req.username;
  const { job, customJobName, tone, similarityThreshold, rollingDays, customTemplates, aiApiKey, aiApiUrl, aiModel, aiEnabled, saveKeyToCloud } = req.body;
  const db = readDB();

  db.users[username].settings = {
    ...db.users[username].settings,
    job: job || db.users[username].settings.job,
    customJobName: customJobName !== undefined ? String(customJobName) : db.users[username].settings.customJobName,
    tone: tone || db.users[username].settings.tone,
    similarityThreshold: similarityThreshold !== undefined ? similarityThreshold : db.users[username].settings.similarityThreshold,
    rollingDays: rollingDays !== undefined ? Number(rollingDays) : db.users[username].settings.rollingDays || 7,
    customTemplates: customTemplates || db.users[username].settings.customTemplates,
    aiApiKey: aiApiKey !== undefined ? aiApiKey : db.users[username].settings.aiApiKey,
    aiApiUrl: aiApiUrl !== undefined ? aiApiUrl : db.users[username].settings.aiApiUrl,
    aiModel: aiModel !== undefined ? aiModel : db.users[username].settings.aiModel,
    aiEnabled: aiEnabled !== undefined ? !!aiEnabled : db.users[username].settings.aiEnabled,
    saveKeyToCloud: saveKeyToCloud !== undefined ? !!saveKeyToCloud : db.users[username].settings.saveKeyToCloud
  };

  if (writeDB(db)) {
    res.json({ success: true, settings: db.users[username].settings });
  } else {
    res.status(500).json({ error: '保存配置失败' });
  }
});

// API: 恢复出厂设置 (支持单用户维度重置)
router.post('/reset', (req, res) => {
  const username = req.username;
  const db = readDB();

  if (db.users[username]) {
    db.users[username].logs = {};
    db.users[username].settings = createDefaultSettings();
    if (writeDB(db)) {
      return res.json({ success: true });
    }
  }
  res.status(500).json({ error: '重置数据库失败' });
});

export default router;
