import { enqueue, flushOfflineQueue, OfflineOp } from './offlineQueue';

export interface LogEntry {
  title: string;          // 日志名称
  hours: number;          // 工时
  cooperation: boolean;   // 部门协作
  difficulty: boolean;    // 工作难点
  content: string;        // 日志内容
  job: string;            // 岗位
  customJobName?: string; // 自定义岗位名称
  tone: string;           // 风格
  isAutoGenerated: boolean;
  isImported?: boolean;   // 是否从外部 Excel 批量导入
  updatedAt: string;
  history?: LogSnapshot[]; // 修改历史快照（最多保留 10 条）
  deletedAt?: string;      // 回收站删除时间戳（软删除标记）
}

/** 日志历史版本快照（不含 history 自身，避免嵌套） */
export interface LogSnapshot {
  title: string;
  hours: number;
  cooperation: boolean;
  difficulty: boolean;
  content: string;
  job?: string;
  customJobName?: string;
  tone?: string;
  updatedAt?: string;
  versionAt?: string;
}

export type JobType = 'backend' | 'frontend' | 'fullstack' | 'tester' | 'designer' | 'pm' | 'devops' | 'custom';

export interface ModelOption {
  id: string;
  name: string;
  isFree: boolean;
}

export interface LocalAISettings {
  aiEnabled: boolean;
  aiApiKey: string;
  aiApiUrl: string;
  aiModel: string;
}

export interface Settings {
  job: JobType | string;
  customJobName?: string;
  tone: string;
  similarityThreshold: number;
  rollingDays: number;    // 滚动补录期限天数
  aiEnabled: boolean;     // 是否启用在线 AI 智能生成
  aiApiKey: string;       // AI 平台的 API 密钥
  aiApiUrl: string;       // AI 平台的 API 基准地址
  aiModel: string;        // 使用的模型标识
  saveKeyToCloud?: boolean; // 是否允许在云端保存密钥
  customTemplates?: string;
}

export interface AppData {
  logs: Record<string, LogEntry>;
  trash?: Record<string, LogEntry>;  // 回收站（软删除的日志）
  settings: Settings;
  reports?: Record<string, string>;  // 周报存储，以 weekKey (YYYY-Ww) 索引
}

// 后端 API 基准地址。统一使用相对路径，开发环境由 Vite proxy 转发，生产环境由同源托管直接响应
export const BACKEND_URL = '';

export function getAuthToken(): string {
  return localStorage.getItem('winner_daily_token') || '';
}

export function setAuthToken(token: string) {
  if (token) {
    localStorage.setItem('winner_daily_token', token);
  } else {
    localStorage.removeItem('winner_daily_token');
  }
}

export function removeAuthToken() {
  localStorage.removeItem('winner_daily_token');
}

export function getAuthHeaders(customHeaders: Record<string, string> = {}): Record<string, string> {
  const token = getAuthToken();
  const headers: Record<string, string> = {
    ...customHeaders
  };
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
    headers['X-Auth-Token'] = token;
  }
  return headers;
}

/** 请求默认超时（ms）。远端部署下 2s 过于激进，会把慢响应误判成离线 */
const REQUEST_TIMEOUT_MS = 8000;
/** 离线队列回放时的单条请求超时（ms） */
const SYNC_TIMEOUT_MS = 15000;

/** 登录态失效事件名，App 层监听后强制重新登录 */
export const AUTH_EXPIRED_EVENT = 'winner-daily-auth-expired';

/**
 * 请求三态结果。区分「网络不可达」与「服务端明确拒绝」是关键：
 * 前者可以安全降级入队等待回放，后者重试无意义，必须向用户暴露。
 */
export type ApiOutcome =
  | { status: 'ok'; res: Response }
  | { status: 'offline'; reason: string }
  | { status: 'rejected'; httpStatus: number; reason: string };

function notifyAuthExpired(reason: string) {
  removeAuthToken();
  try {
    window.dispatchEvent(new CustomEvent(AUTH_EXPIRED_EVENT, { detail: { reason } }));
  } catch (e) { /* 非浏览器环境忽略 */ }
}

/** 从错误响应中提取可读原因，HTML 响应（如 SPA 通配兜底）不作为文案 */
async function readErrorMessage(res: Response): Promise<string> {
  try {
    const text = await res.text();
    try {
      const data = JSON.parse(text);
      if (data && typeof data.error === 'string' && data.error.trim()) return data.error.trim();
    } catch (e) { /* 非 JSON 响应，回退原文 */ }
    if (text.trim() && !text.trimStart().startsWith('<')) return text.trim().slice(0, 200);
  } catch (e) { /* 响应体读取失败 */ }
  if (res.status === 401 || res.status === 403) return '登录凭证已失效，请重新登录。';
  return `服务端返回 HTTP ${res.status}`;
}

/**
 * 统一后端请求封装，返回三态结果：
 *  - ok       2xx 成功
 *  - offline  网络不可达 / 超时 / 网关不可用（502/503/504）→ 可安全入队回放
 *  - rejected 服务端明确拒绝（401/403/其他 4xx/5xx）→ 禁止入队，必须上报用户
 */
async function apiRequest(
  path: string,
  init: RequestInit = {},
  timeoutMs: number = REQUEST_TIMEOUT_MS
): Promise<ApiOutcome> {
  let res: Response;
  try {
    res = await fetch(`${BACKEND_URL}${path}`, { ...init, signal: AbortSignal.timeout(timeoutMs) });
  } catch (e: any) {
    const reason = e && e.name === 'TimeoutError'
      ? `请求超时（已等待 ${timeoutMs}ms）`
      : '后端服务不可达';
    return { status: 'offline', reason };
  }

  if (res.ok) return { status: 'ok', res };

  // 网关/服务暂时不可用等同于后端离线，入队回放是安全的
  if (res.status === 502 || res.status === 503 || res.status === 504) {
    return { status: 'offline', reason: `后端网关暂不可用（HTTP ${res.status}）` };
  }

  const reason = await readErrorMessage(res);
  if (res.status === 401 || res.status === 403) {
    notifyAuthExpired(reason);
  }
  return { status: 'rejected', httpStatus: res.status, reason };
}

// 默认配置
export const DEFAULT_SETTINGS: Settings = {
  job: 'frontend',
  customJobName: '',
  tone: 'professional',
  similarityThreshold: 50,
  rollingDays: 7,          // 默认允许补录最近7天
  aiEnabled: false,        // 默认不开启，由用户自主配置打通
  aiApiKey: '',
  aiApiUrl: 'https://openrouter.ai/api/v1',
  aiModel: 'openrouter/free', // 默认使用 OpenRouter 免费自动路由，避免具体免费模型 ID 失效
  saveKeyToCloud: true    // 新账号默认开启云端备份密钥
};

export const DEFAULT_AI_API_URL = DEFAULT_SETTINGS.aiApiUrl;
export const DEFAULT_AI_MODEL = DEFAULT_SETTINGS.aiModel;

export function isOpenRouterApiUrl(aiApiUrl: string = DEFAULT_AI_API_URL): boolean {
  return (aiApiUrl || '').toLowerCase().includes('openrouter.ai');
}

/**
 * 获取当前用户名：优先从 JWT token 中解码（避免信赖 localStorage 明文），
 * 降级从 localStorage 读取（兼容旧版本）。
 */
export function getCurrentUser(): string {
  const token = getAuthToken();
  if (token) {
    const parts = token.split('.');
    if (parts.length === 2) {
      try {
        const raw = atob(parts[0]);
        const payload = JSON.parse(raw);
        if (payload && payload.u) return payload.u;
      } catch (e) { /* 忽略解析失败 */ }
    }
  }
  return (localStorage.getItem('winner_daily_user') || '').trim().toLowerCase() || 'admin';
}

export function notifySettingsChanged() {
  window.dispatchEvent(new CustomEvent('winner-daily-settings-updated'));
}

function safeParseJSON<T>(raw: string | null): T | null {
  if (!raw) return null;
  try {
    return JSON.parse(raw) as T;
  } catch (e) {
    return null;
  }
}

export function getUserAISettings(user: string = getCurrentUser()): Partial<LocalAISettings> {
  const scoped = safeParseJSON<Partial<LocalAISettings>>(localStorage.getItem(`winner_daily_ai_settings_${user}`));
  if (scoped) return scoped;
  return safeParseJSON<Partial<LocalAISettings>>(localStorage.getItem('winner_daily_ai_settings')) || {};
}

export function saveUserAISettings(settings: Partial<LocalAISettings>, user: string = getCurrentUser()) {
  const nextSettings = {
    ...getUserAISettings(user),
    ...settings
  };
  localStorage.setItem(`winner_daily_ai_settings_${user}`, JSON.stringify(nextSettings));
  localStorage.setItem('winner_daily_ai_settings', JSON.stringify(nextSettings));
  notifySettingsChanged();
}

function getModelCacheKey(aiApiUrl: string = DEFAULT_AI_API_URL, user: string = getCurrentUser()) {
  return `winner_daily_cached_models_${user}_${encodeURIComponent(aiApiUrl || DEFAULT_AI_API_URL)}`;
}

export function loadCachedModels(aiApiUrl: string = DEFAULT_AI_API_URL, user: string = getCurrentUser()): ModelOption[] | null {
  const scoped = safeParseJSON<ModelOption[]>(localStorage.getItem(getModelCacheKey(aiApiUrl, user)));
  if (Array.isArray(scoped)) return scoped;

  if (!isOpenRouterApiUrl(aiApiUrl)) return null;

  const legacy = safeParseJSON<ModelOption[]>(localStorage.getItem('winner_daily_cached_models'));
  return Array.isArray(legacy) ? legacy : null;
}

export function saveCachedModels(models: ModelOption[], aiApiUrl: string = DEFAULT_AI_API_URL, user: string = getCurrentUser()) {
  localStorage.setItem(getModelCacheKey(aiApiUrl, user), JSON.stringify(models));
  notifySettingsChanged();
}

// 内存中的临时数据缓存，降级时使用
let memoryData: AppData = {
  logs: {},
  trash: {},
  reports: {},
  settings: DEFAULT_SETTINGS
};

// 从 LocalStorage 中读取
function getLocalStorageData(): AppData {
  try {
    const raw = localStorage.getItem('winner_daily_data');
    if (raw) {
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error('读取 LocalStorage 失败:', e);
  }
  return { logs: {}, trash: {}, reports: {}, settings: DEFAULT_SETTINGS };
}

// 写入 LocalStorage
function setLocalStorageData(data: AppData) {
  try {
    localStorage.setItem('winner_daily_data', JSON.stringify(data));
  } catch (e) {
    console.error('写入 LocalStorage 失败:', e);
  }
}

/**
 * 获取全部数据（日志+配置）
 */
export async function fetchAllData(): Promise<{ data: AppData; isOffline: boolean; error?: string }> {
  const outcome = await apiRequest('/api/data', { headers: getAuthHeaders() });

  if (outcome.status === 'ok') {
    const data = await outcome.res.json();
    memoryData = data;
    // 同步写入本地 LocalStorage 备份
    setLocalStorageData(data);
    return { data, isOffline: false };
  }

  // 读取失败时仍回落本地缓存（比白屏可用），但把服务端拒绝的原因透出给调用方
  const localData = getLocalStorageData();
  memoryData = localData;

  if (outcome.status === 'rejected') {
    console.warn('[storage] 后端拒绝了数据读取请求:', outcome.httpStatus, outcome.reason);
    return { data: localData, isOffline: true, error: outcome.reason };
  }

  console.warn('[storage] 后端服务不可达，降级为 LocalStorage 离线模式:', outcome.reason);
  return { data: localData, isOffline: true };
}

/**
 * 保存日志
 */
export async function saveLog(
  date: string,
  logData: Omit<LogEntry, 'updatedAt'>
): Promise<{ success: boolean; isOffline: boolean; error?: string }> {
  const payload = { date, ...logData };

  const writeLocal = () => {
    memoryData.logs[date] = {
      ...logData,
      updatedAt: new Date().toISOString()
    };
    setLocalStorageData(memoryData);
  };

  const outcome = await apiRequest('/api/logs', {
    method: 'POST',
    headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
    body: JSON.stringify(payload)
  });

  if (outcome.status === 'ok') {
    writeLocal();
    return { success: true, isOffline: false };
  }

  // 服务端明确拒绝：重试无意义，不得入队，直接把失败原因交还调用方
  if (outcome.status === 'rejected') {
    return { success: false, isOffline: false, error: outcome.reason };
  }

  // 仅「网络不可达」才降级为本地存储并入队等待回放
  writeLocal();
  enqueue({ kind: 'save_log', date, payload });
  return { success: true, isOffline: true };
}

/**
 * 删除日志（软删除：移入回收站 trash，可在设置/回收站恢复）
 */
export async function deleteLog(date: string): Promise<{ success: boolean; isOffline: boolean; error?: string }> {
  // 本地同步先将旧日志快照移入回收站
  const moveToLocalTrash = () => {
    if (memoryData.logs[date]) {
      memoryData.trash = memoryData.trash || {};
      memoryData.trash[date] = {
        ...memoryData.logs[date],
        deletedAt: new Date().toISOString()
      };
      delete memoryData.logs[date];
      setLocalStorageData(memoryData);
      return true;
    }
    return false;
  };

  const outcome = await apiRequest(`/api/logs/${date}`, {
    method: 'DELETE',
    headers: getAuthHeaders()
  });

  if (outcome.status === 'ok') {
    moveToLocalTrash();
    return { success: true, isOffline: false };
  }

  // 服务端拒绝时保持本地不动，避免本地与服务器状态分叉
  if (outcome.status === 'rejected') {
    return { success: false, isOffline: false, error: outcome.reason };
  }

  moveToLocalTrash();
  enqueue({ kind: 'delete_log', date });
  return { success: true, isOffline: true };
}

/**
 * 从回收站恢复指定日期的日志
 */
export async function restoreLog(date: string): Promise<{ success: boolean; isOffline: boolean; error?: string }> {
  const restoreLocally = (): boolean => {
    if (memoryData.trash && memoryData.trash[date]) {
      const cleanLog = { ...memoryData.trash[date] };
      delete cleanLog.deletedAt;
      memoryData.logs[date] = cleanLog;
      delete memoryData.trash[date];
      setLocalStorageData(memoryData);
      return true;
    }
    return false;
  };

  const outcome = await apiRequest(`/api/logs/${date}/restore`, {
    method: 'POST',
    headers: getAuthHeaders()
  });

  if (outcome.status === 'ok') {
    restoreLocally();
    return { success: true, isOffline: false };
  }

  if (outcome.status === 'rejected') {
    return { success: false, isOffline: false, error: outcome.reason };
  }

  const ok = restoreLocally();
  if (ok) enqueue({ kind: 'restore_log', date });
  return { success: ok, isOffline: true };
}

/**
 * 清空回收站（不可恢复，彻底物理删除）
 */
export async function clearTrash(): Promise<{ success: boolean; isOffline: boolean; error?: string }> {
  const outcome = await apiRequest('/api/trash/clear', {
    method: 'POST',
    headers: getAuthHeaders()
  });

  const clearLocal = () => {
    memoryData.trash = {};
    setLocalStorageData(memoryData);
  };

  if (outcome.status === 'ok') {
    clearLocal();
    return { success: true, isOffline: false };
  }

  if (outcome.status === 'rejected') {
    return { success: false, isOffline: false, error: outcome.reason };
  }

  clearLocal();
  enqueue({ kind: 'clear_trash' });
  return { success: true, isOffline: true };
}

/**
 * 保存用户配置
 */
export async function saveSettings(
  settings: Partial<Settings>
): Promise<{ success: boolean; isOffline: boolean; error?: string }> {
  const outcome = await apiRequest('/api/settings', {
    method: 'POST',
    headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
    body: JSON.stringify(settings)
  });

  const writeLocal = () => {
    memoryData.settings = { ...memoryData.settings, ...settings };
    setLocalStorageData(memoryData);
  };

  if (outcome.status === 'ok') {
    writeLocal();
    return { success: true, isOffline: false };
  }

  if (outcome.status === 'rejected') {
    return { success: false, isOffline: false, error: outcome.reason };
  }

  writeLocal();
  enqueue({ kind: 'save_settings', payload: settings });
  return { success: true, isOffline: true };
}

/**
 * 手动覆盖本地所有数据
 */
export async function importAllData(
  data: AppData
): Promise<{ success: boolean; isOffline: boolean; error?: string; failedDates?: string[] }> {
  memoryData = data;
  setLocalStorageData(data);

  const settingsOutcome = await apiRequest('/api/settings', {
    method: 'POST',
    headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
    body: JSON.stringify(data.settings)
  });

  // 后端不可达：整份数据已落本地，配置与日志一并入队待回放
  if (settingsOutcome.status === 'offline') {
    enqueue({ kind: 'save_settings', payload: data.settings });
    for (const [date, log] of Object.entries(data.logs)) {
      enqueue({ kind: 'save_log', date, payload: { date, ...log } });
    }
    return { success: true, isOffline: true };
  }

  if (settingsOutcome.status === 'rejected') {
    return { success: false, isOffline: false, error: settingsOutcome.reason };
  }

  // 逐条写入日志，记录真正失败的日期而非静默忽略
  const failedDates: string[] = [];
  let lastError: string | undefined;
  for (const [date, log] of Object.entries(data.logs)) {
    const outcome = await apiRequest('/api/logs', {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify({ date, ...log })
    });
    if (outcome.status === 'ok') continue;

    lastError = outcome.reason;
    if (outcome.status === 'offline') {
      // 中途掉线：剩余条目全部入队，保证最终一致
      enqueue({ kind: 'save_log', date, payload: { date, ...log } });
      continue;
    }
    failedDates.push(date);
  }

  if (failedDates.length > 0) {
    return {
      success: false,
      isOffline: false,
      error: `${failedDates.length} 条日志被服务端拒绝（${lastError || '原因未知'}）`,
      failedDates
    };
  }

  return { success: true, isOffline: false };
}

/**
 * 还原出厂设置，清空所有日志与配置
 */
export async function resetAllData(): Promise<{ success: boolean; isOffline: boolean; error?: string }> {
  const outcome = await apiRequest('/api/reset', {
    method: 'POST',
    headers: getAuthHeaders()
  });

  const clearLocal = () => {
    memoryData = {
      logs: {},
      trash: {},
      reports: {},
      settings: { ...DEFAULT_SETTINGS }
    };
    setLocalStorageData(memoryData);
  };

  if (outcome.status === 'ok') {
    clearLocal();
    return { success: true, isOffline: false };
  }

  // 服务端拒绝重置时绝不清本地数据，否则会造成不可恢复的单边数据丢失
  if (outcome.status === 'rejected') {
    return { success: false, isOffline: false, error: outcome.reason };
  }

  // 离线模式降级清理，并入队待网络恢复后重放
  localStorage.removeItem('winner_daily_data');
  clearLocal();
  enqueue({ kind: 'reset' });
  return { success: true, isOffline: true };
}

/**
 * 同步当前用户年挂的离线操作队列（网络恢复自动回放）。
 * 逐条执行真实服务器请求，成功后移除队列条目。
 * 供 App 挂载时 / 网络恢复时调用。
 */
export async function syncOfflineOperations(): Promise<{
  successCount: number;
  failCount: number;
  done: boolean;
  droppedCount: number;
  lastError?: string;
}> {
  /** 把单条离线操作映射为一次真实请求 */
  const runQueuedOp = async (op: OfflineOp): Promise<ApiOutcome> => {
    const jsonHeaders = getAuthHeaders({ 'Content-Type': 'application/json' });

    if (op.kind === 'reset') {
      return apiRequest('/api/reset', { method: 'POST', headers: getAuthHeaders() }, SYNC_TIMEOUT_MS);
    }
    if (op.kind === 'delete_log' && op.date) {
      return apiRequest(`/api/logs/${op.date}`, { method: 'DELETE', headers: getAuthHeaders() }, SYNC_TIMEOUT_MS);
    }
    if (op.kind === 'restore_log' && op.date) {
      return apiRequest(`/api/logs/${op.date}/restore`, { method: 'POST', headers: getAuthHeaders() }, SYNC_TIMEOUT_MS);
    }
    if (op.kind === 'clear_trash') {
      return apiRequest('/api/trash/clear', { method: 'POST', headers: getAuthHeaders() }, SYNC_TIMEOUT_MS);
    }
    if (op.kind === 'save_log' && op.date && op.payload) {
      return apiRequest('/api/logs', {
        method: 'POST',
        headers: jsonHeaders,
        body: JSON.stringify(op.payload)
      }, SYNC_TIMEOUT_MS);
    }
    if (op.kind === 'save_settings' && op.payload) {
      return apiRequest('/api/settings', {
        method: 'POST',
        headers: jsonHeaders,
        body: JSON.stringify(op.payload)
      }, SYNC_TIMEOUT_MS);
    }
    if (op.kind === 'save_report' && op.payload && op.payload.weekKey) {
      return apiRequest(`/api/reports/${op.payload.weekKey}`, {
        method: 'POST',
        headers: jsonHeaders,
        body: JSON.stringify({ content: op.payload.content })
      }, SYNC_TIMEOUT_MS);
    }

    // 结构不完整的历史遗留条目，直接视为已处理，避免永久堵塞队列
    console.warn('[offlineQueue] 丢弃结构不完整的历史条目:', op.kind, op.date);
    return { status: 'ok', res: new Response(null, { status: 204 }) };
  };

  let droppedCount = 0;
  let lastError: string | undefined;

  const result = await flushOfflineQueue(async (op) => {
    const outcome = await runQueuedOp(op);
    if (outcome.status === 'ok') return true;

    lastError = outcome.reason;

    // 网络问题：保留队列，下一轮重试
    if (outcome.status === 'offline') return false;

    // 登录态失效：保留队列，用户重新登录后即可完整回放（notifyAuthExpired 已通知 UI）
    if (outcome.httpStatus === 401 || outcome.httpStatus === 403) return false;

    // 服务端暂时性故障：保留队列重试
    if (outcome.httpStatus >= 500) return false;

    // 其余 4xx 为永久性拒绝（如载荷非法），重试永远不会成功。
    // 必须丢弃，否则这条「毒丸」会把整个 FIFO 队列永久堵死。
    droppedCount++;
    console.error(
      '[offlineQueue] 操作被服务端永久拒绝，已从队列移除:',
      op.kind, op.date, outcome.httpStatus, outcome.reason
    );
    return true;
  });

  // flushOfflineQueue 把「丢弃」也计为处理成功，这里扣除，
  // 保证 successCount 语义是「真正同步落盘的条数」，不虚报给用户。
  return {
    ...result,
    successCount: Math.max(0, result.successCount - droppedCount),
    droppedCount,
    lastError
  };
}

import { DirectionOption } from '../types/ai';
import { generateLocalDirectionSuggestions } from './generator';

/**
 * 获取 AI 启发式工作方向推荐 (5 个切入点卡片)
 */
export async function fetchAIDirections(params: {
  job: string;
  customJobName?: string;
  mode: string;
  platform?: string;
  recentLogs?: any[];
  aiApiKey?: string;
  aiApiUrl?: string;
  aiModel?: string;
}): Promise<{ success: boolean; directions: DirectionOption[]; isOffline: boolean }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/ai/directions`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(params),
      signal: AbortSignal.timeout(180000)
    });

    if (res.ok) {
      const data = await res.json();
      if (data && data.directions && Array.isArray(data.directions) && data.directions.length > 0) {
        return { success: true, directions: data.directions, isOffline: !!data.isOffline };
      }
    }
  } catch (e) {
    console.warn('在线拉取方向建议失败，自动无缝降级为本地场景库:', e);
  }

  // 离线/兜底生成
  const localDirs = generateLocalDirectionSuggestions(params.job, params.mode, params.customJobName, params.recentLogs, params.platform);
  return { success: true, directions: localDirs, isOffline: true };
}

/**
 * AI 智能周报提炼与归纳总结
 */
export async function generateAIWeeklyReport(params: {
  job: string;
  customJobName?: string;
  startDate: string;
  endDate: string;
  weekLogs: Array<{
    date: string;
    dayName: string;
    title: string;
    hours: number;
    cooperation: boolean;
    difficulty: boolean;
    content: string;
  }>;
  aiApiKey?: string;
  aiApiUrl?: string;
  aiModel?: string;
}): Promise<{ success: boolean; report?: string; error?: string }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/ai/weekly`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(params),
      signal: AbortSignal.timeout(180000)
    });

    const data = await res.json();
    if (res.ok && data.success && data.report) {
      return { success: true, report: data.report };
    }
    return { success: false, error: data.error || '生成周报失败' };
  } catch (err: any) {
    return { success: false, error: err.message || '网络请求超时' };
  }
}

/**
 * 保存指定周次的周报内容（持久化，历史可回看）
 */
export async function saveWeeklyReport(
  weekKey: string,
  content: string
): Promise<{ success: boolean; isOffline: boolean; error?: string }> {
  const updateLocal = () => {
    memoryData.reports = memoryData.reports || {};
    memoryData.reports[weekKey] = content;
    setLocalStorageData(memoryData);
  };

  const outcome = await apiRequest(`/api/reports/${weekKey}`, {
    method: 'POST',
    headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
    body: JSON.stringify({ content })
  });

  if (outcome.status === 'ok') {
    updateLocal();
    return { success: true, isOffline: false };
  }

  if (outcome.status === 'rejected') {
    return { success: false, isOffline: false, error: outcome.reason };
  }

  updateLocal();
  enqueue({ kind: 'save_report', payload: { weekKey, content } });
  return { success: true, isOffline: true };
}
