import { enqueue, flushOfflineQueue, OfflineOp } from './offlineQueue';

export interface LogEntry {
  title: string;          // 日志名称
  hours: number;          // 工时
  cooperation: boolean;   // 部门协作
  difficulty: boolean;    // 工作难点
  content: string;        // 日志内容
  job: string;            // 岗位
  customJobName?: string; // 自定义岗位名称
  tone: string;           // 风格
  isAutoGenerated: boolean;
  isImported?: boolean;   // 是否从外部 Excel 批量导入
  updatedAt: string;
  history?: LogSnapshot[]; // 修改历史快照（最多保留 10 条）
  deletedAt?: string;      // 回收站删除时间戳（软删除标记）
}

/** 日志历史版本快照（不含 history 自身，避免嵌套） */
export interface LogSnapshot {
  title: string;
  hours: number;
  cooperation: boolean;
  difficulty: boolean;
  content: string;
  job?: string;
  customJobName?: string;
  tone?: string;
  updatedAt?: string;
  versionAt?: string;
}

export type JobType = 'backend' | 'frontend' | 'fullstack' | 'tester' | 'designer' | 'pm' | 'devops' | 'custom';

export interface ModelOption {
  id: string;
  name: string;
  isFree: boolean;
}

export interface LocalAISettings {
  aiEnabled: boolean;
  aiApiKey: string;
  aiApiUrl: string;
  aiModel: string;
}

export interface Settings {
  job: JobType | string;
  customJobName?: string;
  tone: string;
  similarityThreshold: number;
  rollingDays: number;    // 滚动补录期限天数
  aiEnabled: boolean;     // 是否启用在线 AI 智能生成
  aiApiKey: string;       // AI 平台的 API 密钥
  aiApiUrl: string;       // AI 平台的 API 基准地址
  aiModel: string;        // 使用的模型标识
  saveKeyToCloud?: boolean; // 是否允许在云端保存密钥
  customTemplates?: string;
}

export interface AppData {
  logs: Record<string, LogEntry>;
  trash?: Record<string, LogEntry>;  // 回收站（软删除的日志）
  settings: Settings;
  reports?: Record<string, string>;  // 周报存储，以 weekKey (YYYY-Ww) 索引
}

// 后端 API 基准地址。统一使用相对路径，开发环境由 Vite proxy 转发，生产环境由同源托管直接响应
export const BACKEND_URL = '';

export function getAuthToken(): string {
  return localStorage.getItem('winner_daily_token') || '';
}

export function setAuthToken(token: string) {
  if (token) {
    localStorage.setItem('winner_daily_token', token);
  } else {
    localStorage.removeItem('winner_daily_token');
  }
}

export function removeAuthToken() {
  localStorage.removeItem('winner_daily_token');
}

export function getAuthHeaders(customHeaders: Record<string, string> = {}): Record<string, string> {
  const token = getAuthToken();
  const headers: Record<string, string> = {
    ...customHeaders
  };
  if (token) {
    headers['Authorization'] = `Bearer ${token}`;
    headers['X-Auth-Token'] = token;
  }
  return headers;
}

// 默认配置
const DEFAULT_SETTINGS: Settings = {
  job: 'frontend',
  customJobName: '',
  tone: 'professional',
  similarityThreshold: 50,
  rollingDays: 7,          // 默认允许补录最近7天
  aiEnabled: false,        // 默认不开启，由用户自主配置打通
  aiApiKey: '',
  aiApiUrl: 'https://openrouter.ai/api/v1',
  aiModel: 'openrouter/free', // 默认使用 OpenRouter 免费自动路由，避免具体免费模型 ID 失效
  saveKeyToCloud: true    // 新账号默认开启云端备份密钥
};

export const DEFAULT_AI_API_URL = DEFAULT_SETTINGS.aiApiUrl;
export const DEFAULT_AI_MODEL = DEFAULT_SETTINGS.aiModel;

export function isOpenRouterApiUrl(aiApiUrl: string = DEFAULT_AI_API_URL): boolean {
  return (aiApiUrl || '').toLowerCase().includes('openrouter.ai');
}

/**
 * 获取当前用户名：优先从 JWT token 中解码（避免信赖 localStorage 明文），
 * 降级从 localStorage 读取（兼容旧版本）。
 */
export function getCurrentUser(): string {
  const token = getAuthToken();
  if (token) {
    const parts = token.split('.');
    if (parts.length === 2) {
      try {
        const raw = atob(parts[0]);
        const payload = JSON.parse(raw);
        if (payload && payload.u) return payload.u;
      } catch (e) { /* 忽略解析失败 */ }
    }
  }
  return (localStorage.getItem('winner_daily_user') || '').trim().toLowerCase() || 'admin';
}

export function notifySettingsChanged() {
  window.dispatchEvent(new CustomEvent('winner-daily-settings-updated'));
}

function safeParseJSON<T>(raw: string | null): T | null {
  if (!raw) return null;
  try {
    return JSON.parse(raw) as T;
  } catch (e) {
    return null;
  }
}

export function getUserAISettings(user: string = getCurrentUser()): Partial<LocalAISettings> {
  const scoped = safeParseJSON<Partial<LocalAISettings>>(localStorage.getItem(`winner_daily_ai_settings_${user}`));
  if (scoped) return scoped;
  return safeParseJSON<Partial<LocalAISettings>>(localStorage.getItem('winner_daily_ai_settings')) || {};
}

export function saveUserAISettings(settings: Partial<LocalAISettings>, user: string = getCurrentUser()) {
  const nextSettings = {
    ...getUserAISettings(user),
    ...settings
  };
  localStorage.setItem(`winner_daily_ai_settings_${user}`, JSON.stringify(nextSettings));
  localStorage.setItem('winner_daily_ai_settings', JSON.stringify(nextSettings));
  notifySettingsChanged();
}

function getModelCacheKey(aiApiUrl: string = DEFAULT_AI_API_URL, user: string = getCurrentUser()) {
  return `winner_daily_cached_models_${user}_${encodeURIComponent(aiApiUrl || DEFAULT_AI_API_URL)}`;
}

export function loadCachedModels(aiApiUrl: string = DEFAULT_AI_API_URL, user: string = getCurrentUser()): ModelOption[] | null {
  const scoped = safeParseJSON<ModelOption[]>(localStorage.getItem(getModelCacheKey(aiApiUrl, user)));
  if (Array.isArray(scoped)) return scoped;

  if (!isOpenRouterApiUrl(aiApiUrl)) return null;

  const legacy = safeParseJSON<ModelOption[]>(localStorage.getItem('winner_daily_cached_models'));
  return Array.isArray(legacy) ? legacy : null;
}

export function saveCachedModels(models: ModelOption[], aiApiUrl: string = DEFAULT_AI_API_URL, user: string = getCurrentUser()) {
  localStorage.setItem(getModelCacheKey(aiApiUrl, user), JSON.stringify(models));
  notifySettingsChanged();
}

// 内存中的临时数据缓存，降级时使用
let memoryData: AppData = {
  logs: {},
  trash: {},
  reports: {},
  settings: DEFAULT_SETTINGS
};

// 从 LocalStorage 中读取
function getLocalStorageData(): AppData {
  try {
    const raw = localStorage.getItem('winner_daily_data');
    if (raw) {
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error('读取 LocalStorage 失败:', e);
  }
  return { logs: {}, trash: {}, reports: {}, settings: DEFAULT_SETTINGS };
}

// 写入 LocalStorage
function setLocalStorageData(data: AppData) {
  try {
    localStorage.setItem('winner_daily_data', JSON.stringify(data));
  } catch (e) {
    console.error('写入 LocalStorage 失败:', e);
  }
}

/**
 * 获取全部数据（日志+配置）
 */
export async function fetchAllData(): Promise<{ data: AppData; isOffline: boolean }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/data`, { 
      headers: getAuthHeaders(),
      signal: AbortSignal.timeout(2000) 
    });
    if (res.ok) {
      const data = await res.json();
      memoryData = data;
      // 同步写入本地 LocalStorage 备份
      setLocalStorageData(data);
      return { data, isOffline: false };
    }
  } catch (e) {
    console.warn('后端服务未启动或连接超时，正在降级为 LocalStorage 离线模式');
  }

  // 降级模式：读取 LocalStorage
  const localData = getLocalStorageData();
  memoryData = localData;
  return { data: localData, isOffline: true };
}

/**
 * 保存日志
 */
export async function saveLog(
  date: string,
  logData: Omit<LogEntry, 'updatedAt'>
): Promise<{ success: boolean; isOffline: boolean }> {
  const payload = { date, ...logData };

  try {
    const res = await fetch(`${BACKEND_URL}/api/logs`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(2000)
    });
    if (res.ok) {
      // 同步更新 LocalStorage
      memoryData.logs[date] = {
        ...logData,
        updatedAt: new Date().toISOString()
      };
      setLocalStorageData(memoryData);
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('保存日志至后端失败，正在写入本地 LocalStorage 离线存储');
  }

  // 降级模式：写入 LocalStorage 并入队待同步
  memoryData.logs[date] = {
    ...logData,
    updatedAt: new Date().toISOString()
  };
  setLocalStorageData(memoryData);
  enqueue({ kind: 'save_log', date, payload: { date, ...logData } });
  return { success: true, isOffline: true };
}

/**
 * 删除日志（软删除：移入回收站 trash，可在设置/回收站恢复）
 */
export async function deleteLog(date: string): Promise<{ success: boolean; isOffline: boolean }> {
  // 本地同步先将旧日志快照移入回收站
  const moveToLocalTrash = () => {
    if (memoryData.logs[date]) {
      memoryData.trash = memoryData.trash || {};
      memoryData.trash[date] = {
        ...memoryData.logs[date],
        deletedAt: new Date().toISOString()
      };
      delete memoryData.logs[date];
      setLocalStorageData(memoryData);
      return true;
    }
    return false;
  };

  try {
    const res = await fetch(`${BACKEND_URL}/api/logs/${date}`, {
      method: 'DELETE',
      headers: getAuthHeaders(),
      signal: AbortSignal.timeout(2000)
    });
    if (res.ok) {
      moveToLocalTrash();
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('从后端删除日志失败，正在本地 LocalStorage 离线删除');
  }

  moveToLocalTrash();
  enqueue({ kind: 'delete_log', date });
  return { success: true, isOffline: true };
}

/**
 * 从回收站恢复指定日期的日志
 */
export async function restoreLog(date: string): Promise<{ success: boolean; isOffline: boolean }> {
  const restoreLocally = (): boolean => {
    if (memoryData.trash && memoryData.trash[date]) {
      const { deletedAt: _d, ...cleanLog } = memoryData.trash[date];
      memoryData.logs[date] = cleanLog;
      delete memoryData.trash[date];
      setLocalStorageData(memoryData);
      return true;
    }
    return false;
  };

  try {
    const res = await fetch(`${BACKEND_URL}/api/logs/${date}/restore`, {
      method: 'POST',
      headers: getAuthHeaders(),
      signal: AbortSignal.timeout(2000)
    });
    if (res.ok) {
      restoreLocally();
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('在线恢复日志失败，降级本地恢复');
  }

  const ok = restoreLocally();
  if (ok) enqueue({ kind: 'restore_log', date });
  return { success: ok, isOffline: true };
}

/**
 * 清空回收站（不可恢复，彻底物理删除）
 */
export async function clearTrash(): Promise<{ success: boolean; isOffline: boolean }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/trash/clear`, {
      method: 'POST',
      headers: getAuthHeaders(),
      signal: AbortSignal.timeout(2000)
    });
    if (res.ok) {
      memoryData.trash = {};
      setLocalStorageData(memoryData);
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('在线清空回收站失败，降级本地清空');
  }

  memoryData.trash = {};
  setLocalStorageData(memoryData);
  enqueue({ kind: 'clear_trash' });
  return { success: true, isOffline: true };
}

/**
 * 保存用户配置
 */
export async function saveSettings(
  settings: Partial<Settings>
): Promise<{ success: boolean; isOffline: boolean }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/settings`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(settings),
      signal: AbortSignal.timeout(2000)
    });
    if (res.ok) {
      memoryData.settings = { ...memoryData.settings, ...settings };
      setLocalStorageData(memoryData);
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('保存设置至后端失败，正在写入本地 LocalStorage 离线存储');
  }

  memoryData.settings = { ...memoryData.settings, ...settings };
  setLocalStorageData(memoryData);
  enqueue({ kind: 'save_settings', payload: settings });
  return { success: true, isOffline: true };
}

/**
 * 手动覆盖本地所有数据
 */
export async function importAllData(data: AppData): Promise<{ success: boolean; isOffline: boolean }> {
  memoryData = data;
  setLocalStorageData(data);

  try {
    await fetch(`${BACKEND_URL}/api/settings`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(data.settings),
      signal: AbortSignal.timeout(2000)
    });

    for (const [date, log] of Object.entries(data.logs)) {
      await fetch(`${BACKEND_URL}/api/logs`, {
        method: 'POST',
        headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
        body: JSON.stringify({ date, ...log }),
        signal: AbortSignal.timeout(1500)
      });
    }
    return { success: true, isOffline: false };
  } catch (e) {
    console.warn('同步数据到后端不完全，已完成本地 LocalStorage 的数据恢复');
    return { success: true, isOffline: true };
  }
}

/**
 * 还原出厂设置，清空所有日志与配置
 */
export async function resetAllData(): Promise<{ success: boolean }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/reset`, {
      method: 'POST',
      headers: getAuthHeaders(),
      signal: AbortSignal.timeout(2000)
    });
    if (res.ok) {
      // 清空本地缓存
      memoryData = {
        logs: {},
        trash: {},
        reports: {},
        settings: {
          job: 'frontend',
          customJobName: '',
          tone: 'professional',
          similarityThreshold: 50,
          rollingDays: 7,
          aiEnabled: false,
          aiApiKey: '',
          aiApiUrl: 'https://openrouter.ai/api/v1',
          aiModel: 'openrouter/free',
          saveKeyToCloud: true
        }
      };
      setLocalStorageData(memoryData);
      return { success: true };
    }
  } catch (e) {
    console.warn('后端重置失败，降级本地 LocalStorage 清理');
  }

  // 离线模式降级清理
  localStorage.removeItem('winner_daily_data');
  memoryData = {
    logs: {},
    trash: {},
    reports: {},
    settings: {
      job: 'frontend',
      customJobName: '',
      tone: 'professional',
      similarityThreshold: 50,
      rollingDays: 7,
      aiEnabled: false,
      aiApiKey: '',
      aiApiUrl: 'https://openrouter.ai/api/v1',
      aiModel: 'openrouter/free',
      saveKeyToCloud: true
    }
  };
  setLocalStorageData(memoryData);
  enqueue({ kind: 'reset' });
  return { success: true };
}

/**
 * 同步当前用户年挂的离线操作队列（网络恢复自动回放）。
 * 逐条执行真实服务器请求，成功后移除队列条目。
 * 供 App 挂载时 / 网络恢复时调用。
 */
export async function syncOfflineOperations(): Promise<{ successCount: number; failCount: number; done: boolean }> {
  return flushOfflineQueue(async (op) => {
    try {
      if (op.kind === 'reset') {
        const res = await fetch(`${BACKEND_URL}/api/reset`, {
          method: 'POST',
          headers: getAuthHeaders(),
          signal: AbortSignal.timeout(15000)
        });
        return res.ok;
      }
      if (op.kind === 'delete_log' && op.date) {
        const res = await fetch(`${BACKEND_URL}/api/logs/${op.date}`, {
          method: 'DELETE',
          headers: getAuthHeaders(),
          signal: AbortSignal.timeout(15000)
        });
        return res.ok;
      }
      if (op.kind === 'restore_log' && op.date) {
        const res = await fetch(`${BACKEND_URL}/api/logs/${op.date}/restore`, {
          method: 'POST',
          headers: getAuthHeaders(),
          signal: AbortSignal.timeout(15000)
        });
        return res.ok;
      }
      if (op.kind === 'clear_trash') {
        const res = await fetch(`${BACKEND_URL}/api/trash/clear`, {
          method: 'POST',
          headers: getAuthHeaders(),
          signal: AbortSignal.timeout(15000)
        });
        return res.ok;
      }
      if (op.kind === 'save_log' && op.date && op.payload) {
        const payload = op.payload;
        const res = await fetch(`${BACKEND_URL}/api/logs`, {
          method: 'POST',
          headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
          body: JSON.stringify(payload),
          signal: AbortSignal.timeout(15000)
        });
        return res.ok;
      }
      if (op.kind === 'save_settings' && op.payload) {
        const res = await fetch(`${BACKEND_URL}/api/settings`, {
          method: 'POST',
          headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
          body: JSON.stringify(op.payload),
          signal: AbortSignal.timeout(15000)
        });
        return res.ok;
      }
      if (op.kind === 'save_report' && op.payload && op.payload.weekKey) {
        const res = await fetch(`${BACKEND_URL}/api/reports/${op.payload.weekKey}`, {
          method: 'POST',
          headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
          body: JSON.stringify({ content: op.payload.content }),
          signal: AbortSignal.timeout(15000)
        });
        return res.ok;
      }
      return true;
    } catch (e) {
      console.warn('[offlineQueue] 同步操作失败（下一轮重试）:', op.kind, op.date, e);
      return false;
    }
  });
}

import { DirectionOption } from '../types/ai';
import { generateLocalDirectionSuggestions } from './generator';

/**
 * 获取 AI 启发式工作方向推荐 (5 个切入点卡片)
 */
export async function fetchAIDirections(params: {
  job: string;
  customJobName?: string;
  mode: string;
  recentLogs?: any[];
  aiApiKey?: string;
  aiApiUrl?: string;
  aiModel?: string;
}): Promise<{ success: boolean; directions: DirectionOption[]; isOffline: boolean }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/ai/directions`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(params),
      signal: AbortSignal.timeout(180000)
    });

    if (res.ok) {
      const data = await res.json();
      if (data && data.directions && Array.isArray(data.directions) && data.directions.length > 0) {
        return { success: true, directions: data.directions, isOffline: !!data.isOffline };
      }
    }
  } catch (e) {
    console.warn('在线拉取方向建议失败，自动无缝降级为本地场景库:', e);
  }

  // 离线/兜底生成
  const localDirs = generateLocalDirectionSuggestions(params.job, params.mode, params.customJobName, params.recentLogs);
  return { success: true, directions: localDirs, isOffline: true };
}

/**
 * AI 智能周报提炼与归纳总结
 */
export async function generateAIWeeklyReport(params: {
  job: string;
  customJobName?: string;
  startDate: string;
  endDate: string;
  weekLogs: Array<{
    date: string;
    dayName: string;
    title: string;
    hours: number;
    cooperation: boolean;
    difficulty: boolean;
    content: string;
  }>;
  aiApiKey?: string;
  aiApiUrl?: string;
  aiModel?: string;
}): Promise<{ success: boolean; report?: string; error?: string }> {
  try {
    const res = await fetch(`${BACKEND_URL}/api/ai/weekly`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify(params),
      signal: AbortSignal.timeout(180000)
    });

    const data = await res.json();
    if (res.ok && data.success && data.report) {
      return { success: true, report: data.report };
    }
    return { success: false, error: data.error || '生成周报失败' };
  } catch (err: any) {
    return { success: false, error: err.message || '网络请求超时' };
  }
}

/**
 * 保存指定周次的周报内容（持久化，历史可回看）
 */
export async function saveWeeklyReport(
  weekKey: string,
  content: string
): Promise<{ success: boolean; isOffline: boolean }> {
  // 本地同步更新缓存
  const updateLocal = () => {
    memoryData.reports = memoryData.reports || {};
    memoryData.reports[weekKey] = content;
    setLocalStorageData(memoryData);
  };
  updateLocal();

  try {
    const res = await fetch(`${BACKEND_URL}/api/reports/${weekKey}`, {
      method: 'POST',
      headers: getAuthHeaders({ 'Content-Type': 'application/json' }),
      body: JSON.stringify({ content }),
      signal: AbortSignal.timeout(2000)
    });
    if (res.ok) {
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('周报同步后端失败，已本地保存待网络恢复', e);
  }

  enqueue({ kind: 'save_report', payload: { weekKey, content } });
  return { success: true, isOffline: true };
}
