export interface LogEntry {
  title: string;          // 日志名称
  hours: number;          // 工时
  cooperation: boolean;   // 部门协作
  difficulty: boolean;    // 工作难点
  content: string;        // 日志内容
  job: string;            // 岗位
  tone: string;           // 风格
  isAutoGenerated: boolean;
  updatedAt: string;
}

export interface Settings {
  job: string;
  tone: string;
  similarityThreshold: number;
  rollingDays: number;    // 滚动补录期限天数
  aiEnabled: boolean;     // 是否启用在线 AI 智能生成
  aiApiKey: string;       // AI 平台的 API 密钥
  aiApiUrl: string;       // AI 平台的 API 基准地址
  aiModel: string;        // 使用的模型标识
  customTemplates?: string;
}

export interface AppData {
  logs: Record<string, LogEntry>;
  settings: Settings;
}

// 动态计算后端 API 基准地址。开发环境连 localhost:3001，生产部署环境（如京东云 IP 访问）连网页同源 origin
export const BACKEND_URL = typeof window !== 'undefined'
  ? (window.location.hostname === 'localhost' || window.location.hostname === '127.0.0.1'
    ? 'http://localhost:3001'
    : window.location.origin)
  : 'http://localhost:3001';

// 默认配置
const DEFAULT_SETTINGS: Settings = {
  job: 'frontend',
  tone: 'professional',
  similarityThreshold: 50,
  rollingDays: 7,          // 默认允许补录最近7天
  aiEnabled: false,        // 默认不开启，由用户自主配置打通
  aiApiKey: '',
  aiApiUrl: 'https://openrouter.ai/api/v1',
  aiModel: 'qwen/qwen-3-coder:free' // 默认推荐 Qwen3 Coder 480B 免费版大模型
};

// 内存中的临时数据缓存，降级时使用
let memoryData: AppData = {
  logs: {},
  settings: DEFAULT_SETTINGS
};

// 从 LocalStorage 中读取
function getLocalStorageData(): AppData {
  try {
    const raw = localStorage.getItem('winner_daily_data');
    if (raw) {
      return JSON.parse(raw);
    }
  } catch (e) {
    console.error('读取 LocalStorage 失败:', e);
  }
  return { logs: {}, settings: DEFAULT_SETTINGS };
}

// 写入 LocalStorage
function setLocalStorageData(data: AppData) {
  try {
    localStorage.setItem('winner_daily_data', JSON.stringify(data));
  } catch (e) {
    console.error('写入 LocalStorage 失败:', e);
  }
}

/**
 * 获取全部数据（日志+配置）
 */
export async function fetchAllData(): Promise<{ data: AppData; isOffline: boolean }> {
  try {
    const user = localStorage.getItem('winner_daily_user') || 'admin';
    const res = await fetch(`${BACKEND_URL}/api/data`, { 
      headers: {
        'X-User-Name': user
      },
      signal: AbortSignal.timeout(1500) 
    });
    if (res.ok) {
      const data = await res.json();
      memoryData = data;
      // 同步写入本地 LocalStorage 备份
      setLocalStorageData(data);
      return { data, isOffline: false };
    }
  } catch (e) {
    console.warn('后端服务未启动或连接超时，正在降级为 LocalStorage 离线模式');
  }

  // 降级模式：读取 LocalStorage
  const localData = getLocalStorageData();
  memoryData = localData;
  return { data: localData, isOffline: true };
}

/**
 * 保存日志
 */
export async function saveLog(
  date: string,
  logData: Omit<LogEntry, 'updatedAt'>
): Promise<{ success: boolean; isOffline: boolean }> {
  const payload = { date, ...logData };

  try {
    const user = localStorage.getItem('winner_daily_user') || 'admin';
    const res = await fetch(`${BACKEND_URL}/api/logs`, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'X-User-Name': user
      },
      body: JSON.stringify(payload),
      signal: AbortSignal.timeout(1500)
    });
    if (res.ok) {
      // 同步更新 LocalStorage
      memoryData.logs[date] = {
        ...logData,
        updatedAt: new Date().toISOString()
      };
      setLocalStorageData(memoryData);
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('保存日志至后端失败，正在写入本地 LocalStorage 离线存储');
  }

  // 降级模式：写入 LocalStorage
  memoryData.logs[date] = {
    ...logData,
    updatedAt: new Date().toISOString()
  };
  setLocalStorageData(memoryData);
  return { success: true, isOffline: true };
}

/**
 * 删除日志
 */
export async function deleteLog(date: string): Promise<{ success: boolean; isOffline: boolean }> {
  try {
    const user = localStorage.getItem('winner_daily_user') || 'admin';
    const res = await fetch(`${BACKEND_URL}/api/logs/${date}`, {
      method: 'DELETE',
      headers: {
        'X-User-Name': user
      },
      signal: AbortSignal.timeout(1500)
    });
    if (res.ok) {
      delete memoryData.logs[date];
      setLocalStorageData(memoryData);
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('从后端删除日志失败，正在本地 LocalStorage 离线删除');
  }

  if (memoryData.logs[date]) {
    delete memoryData.logs[date];
    setLocalStorageData(memoryData);
    return { success: true, isOffline: true };
  }
  return { success: false, isOffline: true };
}

/**
 * 保存用户配置
 */
export async function saveSettings(
  settings: Partial<Settings>
): Promise<{ success: boolean; isOffline: boolean }> {
  try {
    const user = localStorage.getItem('winner_daily_user') || 'admin';
    const res = await fetch(`${BACKEND_URL}/api/settings`, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'X-User-Name': user
      },
      body: JSON.stringify(settings),
      signal: AbortSignal.timeout(1500)
    });
    if (res.ok) {
      memoryData.settings = { ...memoryData.settings, ...settings };
      setLocalStorageData(memoryData);
      return { success: true, isOffline: false };
    }
  } catch (e) {
    console.warn('保存设置至后端失败，正在写入本地 LocalStorage 离线存储');
  }

  memoryData.settings = { ...memoryData.settings, ...settings };
  setLocalStorageData(memoryData);
  return { success: true, isOffline: true };
}

/**
 * 手动覆盖本地所有数据
 */
export async function importAllData(data: AppData): Promise<{ success: boolean; isOffline: boolean }> {
  memoryData = data;
  setLocalStorageData(data);

  try {
    const user = localStorage.getItem('winner_daily_user') || 'admin';
    await fetch(`${BACKEND_URL}/api/settings`, {
      method: 'POST',
      headers: { 
        'Content-Type': 'application/json',
        'X-User-Name': user
      },
      body: JSON.stringify(data.settings),
      signal: AbortSignal.timeout(1500)
    });

    for (const [date, log] of Object.entries(data.logs)) {
      await fetch(`${BACKEND_URL}/api/logs`, {
        method: 'POST',
        headers: { 
          'Content-Type': 'application/json',
          'X-User-Name': user
        },
        body: JSON.stringify({ date, ...log }),
        signal: AbortSignal.timeout(1000)
      });
    }
    return { success: true, isOffline: false };
  } catch (e) {
    console.warn('同步数据到后端不完全，已完成本地 LocalStorage 的数据恢复');
    return { success: true, isOffline: true };
  }
}

/**
 * 还原出厂设置，清空所有日志与配置
 */
export async function resetAllData(): Promise<{ success: boolean }> {
  try {
    const user = localStorage.getItem('winner_daily_user') || 'admin';
    const res = await fetch(`${BACKEND_URL}/api/reset`, {
      method: 'POST',
      headers: {
        'X-User-Name': user
      },
      signal: AbortSignal.timeout(1500)
    });
    if (res.ok) {
      // 清空本地缓存
      memoryData = {
        logs: {},
        settings: {
          job: 'frontend',
          tone: 'professional',
          similarityThreshold: 50,
          rollingDays: 7,
          aiEnabled: false,
          aiApiKey: '',
          aiApiUrl: 'https://openrouter.ai/api/v1',
          aiModel: 'qwen/qwen-3-coder:free'
        }
      };
      setLocalStorageData(memoryData);
      return { success: true };
    }
  } catch (e) {
    console.warn('后端重置失败，降级本地 LocalStorage 清理');
  }

  // 离线模式降级清理
  localStorage.removeItem('winner_daily_data');
  memoryData = {
    logs: {},
    settings: {
      job: 'frontend',
      tone: 'professional',
      similarityThreshold: 50,
      rollingDays: 7,
      aiEnabled: false,
      aiApiKey: '',
      aiApiUrl: 'https://openrouter.ai/api/v1',
      aiModel: 'qwen/qwen-3-coder:free'
    }
  };
  setLocalStorageData(memoryData);
  return { success: true };
}
